name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  ARTIFACT_VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'


      - name: Verify go.mod is sane
        run: go mod tidy && git diff --no-patch --exit-code

      - name: Run code lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          args: --timeout=3m

      - name: Install dependencies
        run: go mod download

      - name: Build binaries
        run: |
          GOOS=${{ matrix.goos }} \
          GOARCH=${{ matrix.goarch }} \
          go build \
            -installsuffix "static" \
            -ldflags "                                            \
                -X main.Version=${ARTIFACT_VERSION:-"local"}      \
                -X main.GoVersion=$(go version | cut -d " " -f 3) \
                -X main.Compiler=$(go env CC)                     \
                -X main.Platform=$(go env GOOS)/$(go env GOARCH)  \
            " \
            -o ./ \
            ./...
          mkdir -p dist
          cp dns-lookuper dist/dns-lookuper-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: dns-lookuper-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/
